services:
  facebook-server:
    build:
      context: ./facebook-server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./facebook-server/.env
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    depends_on:
      - facebook-server
    command: ["npm", "run", "start"]
    networks:
      - app-network

  messenger-server:
    build:
      context: ./messenger-server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - ./messenger-server/.env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge